CREATE DATABASE roda;

CREATE TABLE categories (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(50) UNIQUE NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE products (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
description TEXT,
image VARCHAR(300),
category_id INT UNSIGNED NOT NULL,
quantity INT UNSIGNED DEFAULT 1,
price DECIMAL UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE colors (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
name VARCHAR(50) NOT NULL UNIQUE,
valueColor VARCHAR(50) NOT NULL UNIQUE,
PRIMARY KEY (id)
);

CREATE TABLE products_colors (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
product_id INT UNSIGNED NOT NULL,
color_id INT UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (product_id) REFERENCES products(id),
FOREIGN KEY (color_id) REFERENCES colors(id)
);

CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
email VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(200) UNIQUE NOT NULL,
image VARCHAR(200) UNIQUE NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE shoppingCart (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
user_id INT UNSIGNED NOT NULL,
product_id INT UNSIGNED NOT NULL,
quantity INT UNSIGNED NOT NULL,
totalPrice DECIMAL UNSIGNED NOT NULL,
active TINYINT NOT NULL DEFAULT 1,
date DATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_id) REFERENCES users(id),
FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE detailCart (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
shoppingCart_id INT UNSIGNED NOT NULL,
quantity INT UNSIGNED NOT NULL,
actualPrice DECIMAL UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (shoppingCart_id) REFERENCES shoppingCart(id)
);